### PR TITLE
issue-28 - add consent manager

### LINKED ISSUE #28: Add Consent Manager
https://knowledge.truevault.com/article/215-how-to-customize-your-consent-manager-widgets

### PR DESCRIPTION
**Pull request by tmaret**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #28

Test URLs:
- Before: https://main--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor
- After: https://issue-28--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor

### CODE REVIEW

**Comment by tmaret** [comment]
@bstopp you should see the consent manager in place at https://issue-28--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/

**Comment by bstopp** [comment]
Should be in bottom corner? Not seeing it

Cigar_Advisor_-__1_Cigar_Magazine_for_Cigar_Reviews

Don't think it's returning successfully.

**Comment by tmaret** [comment]
Interesting, here's what I see when I clear my cookies

Screenshot 2024-01-24 at 18 04 19

and when I have consent to some cookies there's indeed a button in the bottom left corner
 
Screenshot 2024-01-24 at 18 04 00

**Comment by tmaret** [comment]
However, I also see 
`https://location.truevaultcdn.com` being fetched over and over. I'll address that.

**Comment by bstopp** [comment]
Yeah, i tried an incognito chrome window and didn't see anything. Maybe it's regional?

**Comment by bstopp** [comment]
Don't get it in FireFox either.

**Pull request closed without merging**
