### PR TITLE
Various Styling and Perf Improvements

### LINKED ISSUE #101: 404 Page Styling
Probably the `reset.css` broke this. 

Also missing some articles.

### PR DESCRIPTION
**Pull request by bstopp**
Fix #101 

Test URLs:
- https://bug-styles--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/
- https://bug-styles--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/fragments/404
- https://bug-styles--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/author/john-pullo
- https://bug-styles--famous-smoke-cigaradvisor--hlxsites.hlx.page/cigaradvisor/posts/2023/12/top-10-best-new-cigars-of-2023

### CODE REVIEW

**Comment by tmaret** [comment]
Screenshot 2024-01-23 at 22 30 28

The blog post template seems to break the footer on the posts.

**Comment by bstopp** [comment]
Yep. Got a little too over zealous . Will fix

**Comment by bstopp** [comment]
Fixed(?)

**Review by tmaret — APPROVED** [review]

**Review by kailasnadh790 — COMMENTED** [review]
Commented in the thread: https://cq-dev.slack.com/archives/C066DR1SS22/p1706045283690079

**Pull request merged**
